### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by waaawoo** [waaawoo/furima-34760#16]
#URL
https://furima-34760.herokuapp.com/

# Basic認証のIDとパスワード
・Basic認証「34760」
・パスワード「34760」

# 出品者情報
Email：test1@test
Password：testuser1

#購入者情報
Email：test2@test
Password：testuser2

**Comment by naru6117** [comment]
@waaawoo さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正依頼箇所]

- [x] **ログイン状態のユーザーだけが、商品出品ページへ遷移できるようにしましょう！**
現状、出品するボタンを押しても遷移できません
<img width="1155" alt="Furima34760_と_ruby" src="https://user-images.githubusercontent.com/49669977/110560728-d345c600-8189-11eb-9292-2b77764e5704.png">


修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by waaawoo** [comment]
# what
指摘修正
# why
 修正点
　・出品ボタンをログインユーザーのみ表示
　・ログインユーザーがボタンを押すと商品登録画面へ遷移

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の指摘事項は修正が確認できました(^^)
新たに以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [ ] **商品出品時に登録した情報が見られるようになっているようにしましょう！**
<img width="978" alt="Furima34760" src="https://user-images.githubusercontent.com/49669977/110571246-a0f09480-819a-11eb-80ab-9dc60c4e1022.png">

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by waaawoo** [comment]
# what
指摘修正

# why
商品詳細画面の出品者名が出力される

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTMです✨**　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/49669977/110573211-37728500-819e-11eb-8570-fe8a54df0d47.png)


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
